version: '3'
services:
  broker:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - MOLECULER_TRANSPORTER=NATS
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
